# DataSource Config
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:test
#    username: root
#    password: test

spring:
  application:
    name: tx-cloud-alibaba-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mybatis-plus-test?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 1qaz2wsx
  main:
    allow-bean-definition-overriding: true
server:
  port: 8081

# actuator  相关
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
# cloud 相关
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      web-context-unify: true


# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

